### PR TITLE
Spray and pray: Wall project Airlocks and Other Tidbits

### PR DESCRIPTION
**Pull request by ArcaneMusic**
Oh jesus this is going to go VERY BADLY for me, won't it?

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
arcane I uh

**Comment by ArcaneMusic** [comment]
*I KNOW WHAT I'M DOING*

**Comment by tralezab** [comment]
gl my boy

**Comment by ArcaneMusic** [comment]
WOOOOOOOO

**Comment by LemonInTheDark** [comment]
o7

**Pull request merged**
